#include "glob.h"

/**
 * Convert glob pattern into a regular expression
 *
 * @param glob The pattern to be processed
 *
 * @return char* A pointer to the resulting regular expression
 */
char *glob2regex(char *glob)
{
	char *re = NULL;

	if (glob != NULL)
	{
		re = calloc(strlen(glob) * 2 + 4, sizeof(char));
		if (re == NULL)
		{
			return NULL;
		}

		char *r = re;

		*r++ = '^';
		while (*glob != '\0')
			switch (*glob)
			{
			case '.':
			case '\\':
			case '$':
				*r++ = '\\';
				*r++ = *glob++;
				break;
			case '*':
				*r++ = '.';
				*r++ = *glob++;
				break;
			case '?':
				*r++ = '.';
				glob++;
				break;
			case '/':
				free(re);
				re = NULL;
				break;
			default:
				*r++ = *glob++;
				break;
			}
		if (re)
		{
			*r++ = '$';
			*r = '\0';
		}
	}
	return re;
}

/**
 * Match filename to each pattern given at command line
 *
 * @param flags Pointer to FLAG to be processed
 * @param filename Pointer to filename to be processed
 * @param mode (1) process i flag, (0) process o flag
 *
 * @return int
 */
int matchRegex(FLAG *flags, const char *filename, int mode)
{
	char *globPattern; // Declare char pointer to a glob pattern
	int pattern_count; // Declare integer to hold pattern count
	char **patterns;   // Declare pointer to a pointer that points to patterns array

	// If i mode (flag i is requested)
	if (mode == 1)
	{
		pattern_count = flags->pattern_i_count; // Fill in pre declared pattern count for flag i
		patterns = flags->patterns_i;			// Fill in pre declared patterns array for flag i
	}
	// If o mode (flag o is requetsed)
	else if (mode == 0)
	{
		pattern_count = flags->pattern_o_count; // Fill in pre declared pattern count for flag o
		patterns = flags->patterns_o;			// Fill in pre declared patterns array for flag o
	}
	else
	{
		return 0; // Invalid mode
	}

	for (int i = 0; i < pattern_count; i++)
	{
		globPattern = patterns[i];
		char *regexPattern = glob2regex(globPattern);

		if (regexPattern != NULL)
		{
			regex_t regex;
			if (regcomp(&regex, regexPattern, 0) == 0) // Process regular expression given by glob2regex function
			{
				if (regexec(&regex, filename, 0, NULL, 0) == 0) // Compare if current file matches to regular expression
				{
					regfree(&regex);
					free(regexPattern);
					if (flags->flag_v)
					{
						printf("Matches '%s'\n", patterns[i]); // Print verbose output
					}
					return 1; // Filename matches regular expression generated by pattern
				}
				regfree(&regex); // Reset saved regular expression to process next pattern
			}
			free(regexPattern); // Free allocated memory
		}
	}

	return 0; // Nothing matched
}
